version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: br10db
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
