server:
  port: ${PORT:8082}
  servlet:
    context-path: ${BR10_CONTEXT_PATH:/api}
spring:
  servlet:
    multipart:
      max-file-size: ${BR10_MAX_FILE_SIZE:10MB}
      max-request-size: ${BR10_MAX_REQUEST_SIZE:10MB}
  datasource:
    url: ${BR10_DB_URL:jdbc:postgresql://localhost:5433/br10db}
    username: ${BR10_DB_USERNAME:postgres}
    password: ${BR10_DB_PASSWORD:123456789}
  application:
    name: br10
  data:
    redis:
      host: ${BR10_REDIS_HOST:localhost}
      port: ${BR10_REDIS_PORT:6379}

file:
  upload-dir: ${BR10_UPLOAD_DIR:uploads}

security:
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173/}
  jwt:
    secret: ${BR10_JWT_SECRET:MZl1GC5OHL+km2NKuTrUNH7PcnqMyvbUBzeUVsPGAlqY7BqAGjFcEJgAZTd4ziYB}
    refresh-expiration: ${BR10_JWT_REFRESH_EXPIRATION:86400000}
    jwt-expiration: ${BR10_JWT_EXPIRATION:86400000}