server:
  port: ${PORT:8082}
  servlet:
    context-path: ${BR10_CONTEXT_PATH:/api}
spring:
  profiles:
    active: ${BR10_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: ${BR10_MAX_FILE_SIZE:10MB}
      max-request-size: ${BR10_MAX_REQUEST_SIZE:10MB}
  datasource:
    url: ${BR10_DB_URL:jdbc:postgresql://ep-aged-glitter-a2lnphh0-pooler.eu-central-1.aws.neon.tech/br10db}
    username: ${BR10_DB_USERNAME:neondb_owner}
    password: ${BR10_DB_PASSWORD:npg_9WNinYgzGMb5}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    open-in-view: false
  application:
    name: br10
  data:
    redis:
      database: 0
      password: ${BR10_REDIS_PASSWORD:LFMFMCn0qsmRhuYAUXRPZFzUO7bFOPSi}
      host: ${BR10_REDIS_HOST:redis-16724.c300.eu-central-1-1.ec2.redns.redis-cloud.com}
      port: ${BR10_REDIS_PORT:16724}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    drop-first: false
    default-schema: public
  messages:
    basename: messages
    encoding: utf-8
  thymeleaf:
    encoding: utf-8
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
file:
  upload-dir: ${BR10_UPLOAD_DIR:uploads}
cloudinary:
  cloud-name: ${BR10_CLOUDINARY_CLOUD_NAME:dhhlnrons}
  api-key: ${BR10_CLOUDINARY_CLOUD_NAME:712786691512151}
  api-secret: ${BR10_CLOUDINARY_CLOUD_NAME:AIp9AEAYuHYk_IQqDDozHF4Ew9M}

management:
  endpoint:
    health:
      show-details: always

security:
  auth-rate-limit:
    register:
      max-allowed-attemps: 3
      block-time: 60
    login:
      max-allowed-attemps: 3
      block-time: 60
  otp-config:
    otp-expiration-time: ${BR10_OTP_EXPIRATION_TIME:300}
    otp-try-limit: ${BR10_OTP_LIMIT:3}
    otp-daily-limit: ${BR10_OTP_DAILY_LIMIT:6}
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173/}
  encryption:
    secret: 123456789
    algorithm: AES
    key-size: 128
  jwt:
    secret: ${BR10_JWT_SECRET:MZl1GC5OHL+km2NKuTrUNH7PcnqMyvbUBzeUVsPGAlqY7BqAGjFcEJgAZTd4ziYB}
    refresh-expiration: ${BR10_JWT_REFRESH_EXPIRATION:86400000}
    jwt-expiration: ${BR10_JWT_EXPIRATION:86400000}
  endpoint-white-list:
    - /auth/**
    - /ws/**
    - /swagger-ui/**
    - /actuator/**
    - /app/**
    - /specialities/**
  endpoint-black-list:
    - /auth/logout
decorator:
  datasource:
    p6spy:
      enable-logging: true
      custom-appender-class: fib.br10.core.utility.CustomSQLFormat
      logging: custom

log-level: info


springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/api-docs

  swagger-ui:
    url: /swagger-ui/api-docs
    disable-swagger-default-url: true
    enabled: true