spring:
  datasource:
    url: jdbc:postgresql://ep-flat-field-a4evvzgv-pooler.us-east-1.aws.neon.tech:5432/verceldb
    username: default
    password: gBW5bawvQ3Kj
  data:
    redis:
      host: oregon-redis.render.com
      port: 6379
      password: k5eYhJPwQHi6nQN9Qvr1hG2aDvygYUnI
      username: red-cq8hguuehbks738k9u5g
      ssl:
        enabled: true

  liquibase:
    default-schema: verceldb